### ISSUE TITLE
Options for UI/whichkey?

### ISSUE THREAD

**Issue by emacsomancer** [intrntbrn/motion#1]
The "whichkey" UI is helpful for submenus, or if I forget keybindings/want to see a menu; but it can be a bit distracting when I'm using frequently used commands.

is there a way to control when it is displayed? perhaps something like only displaying when the root key (super_l in the default) is released?

**Comment by intrntbrn** [comment]
There are tons of options to configure it.

There are `toggle_keys`.  You can also configure `hints.delay`. Or you can simply disable hints (`hints.enabled`) for the root menu, and enable it for every submenu individually, which is also how I set it up personally.

**Comment by emacsomancer** [comment]
A combination of disabling hints for the root menu and enabling hints for individual submenus along with `toggle_keys` seems to work.
